<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WINCTRL-6AL1M0F" failures="1" tests="1" name="test(failed)" time="21.73" errors="0" timestamp="2022-12-24T11:06:38 IST">
  <testcase classname="ai.Dalalnew.TestLayer.LoginPageTest" name="verifyLogin" time="3.777">
    <failure type="java.lang.AssertionError" message="did not expect [https://apps.dalalstreet.ai/dashboard] but found [https://apps.dalalstreet.ai/dashboard]">
      <![CDATA[java.lang.AssertionError: did not expect [https://apps.dalalstreet.ai/dashboard] but found [https://apps.dalalstreet.ai/dashboard]
at ai.Dalalnew.TestLayer.LoginPageTest.verifyLogin(LoginPageTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- test(failed) -->
